

language: cpp
dist: bionic
compiler:
- Scons
os:
- linux
before_install:
  - sudo apt-get -y install scons
script:
    - git submodule update --init
    - scons target='x86-unknown-linux' build_config='Debug'
    - scons target='x86-unknown-linux' build_config='Release'

